/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguimientodeitems;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import seguimientodeitems.Control.Estado;
import seguimientodeitems.Control.Users;

/**
 *
 * @author ezequiel_o
 */
public class Administracion extends javax.swing.JFrame {
    private List <Users> lista = new ArrayList<Users>();
    private Users usuario;
    /**
     * Creates new form Administracion
     */
    public Administracion(Users user,List <Users> lista) {
        this.lista=lista;
        this.usuario=user;
        for (Users i : this.lista) {
             modelo.addElement(i.getUsuario());
        }
        
        for (Users i : this.lista) {
             modeloAlta.addElement(i.isAlta());
        }
        
        initComponents();this.setLocationRelativeTo(null); 
    }

    private Administracion() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelo = new DefaultListModel();
        ListaDeUsuariosTabla = new javax.swing.JList<>();
        Confirmar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        modeloAlta = new DefaultListModel();
        ListaAlta = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(51, 255, 255));
        salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(102, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icon (1).png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, -1));

        ListaDeUsuariosTabla.setModel(modelo);
        ListaDeUsuariosTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDeUsuariosTabla.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(ListaDeUsuariosTabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 220));

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 110, -1));

        Borrar.setText("borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        getContentPane().add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 110, -1));

        jButton3.setText("entrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 110, -1));

        Atras.setText("Atraz");
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 110, -1));

        ListaAlta.setModel(modeloAlta);
        ListaAlta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaAlta.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(ListaAlta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 90, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
         
        
         
        lista.get(ListaDeUsuariosTabla.getSelectedIndex()).setAlta(true);
        modelo.removeAllElements();
        for (Users i : this.lista) {
             modeloAlta.addElement(i.isAlta());
        }
        
        ListaAlta.setSelectedIndex(-1);
        ListaDeUsuariosTabla.setSelectedIndex(-1);
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Confirmar;
    private javax.swing.JList<String> ListaAlta;
    private DefaultListModel modeloAlta;
    private javax.swing.JList<String> ListaDeUsuariosTabla;
    private DefaultListModel modelo;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
