/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguimientodeitems;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import seguimientodeitems.Control.Equipo;
import seguimientodeitems.Control.Estado;
import seguimientodeitems.Control.Item;
import seguimientodeitems.Control.LiderProyecto;
import seguimientodeitems.Control.Miembro;

/**
 *
 * @author ezequiel_o
 */
public class Interfaz extends javax.swing.JFrame {
   private List<Item> listaDeItems=  new ArrayList<Item>();
   private  List<Estado> listaDeEstados=  new ArrayList<Estado>();
   private Integer num= new Integer(0);
   private LiderProyecto lider; 
    
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz(LiderProyecto Lider) {
        this.lider=Lider;
        initComponents();this.setLocationRelativeTo(null);jTabbedPane1.setEnabledAt(1,false);jTabbedPane1.setEnabledAt(2,false);
        jTabbedPane1.setEnabledAt(3,false);jTabbedPane1.setEnabledAt(4,true);
                ;
    }

    private Interfaz() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BotonAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelo = new DefaultListModel();
        ListaDeItemsTabla = new javax.swing.JList<>();
        botonBorrar = new javax.swing.JButton();
        campoTextoItem = new javax.swing.JTextField();
        ContadorDeLista = new javax.swing.JLabel();
        BotonModificarItem = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PrioridadItem = new javax.swing.JTextField();
        JlabelFondo1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        BotonAgregarEstado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        modeloEstado = new DefaultListModel();
        ListaDeEstadosTabla = new javax.swing.JList<>();
        botonBorrarEstado = new javax.swing.JButton();
        campoTextoEstado = new javax.swing.JTextField();
        ContadorDeEstados = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        NombreDelItem = new javax.swing.JLabel();
        AtrasEstados = new javax.swing.JButton();
        JlabelFondo3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BotonAgregarEstadosSiguientes = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        modeloEstadosSiguientes = new DefaultListModel();
        ListaDeEstadosSiguientesTabla = new javax.swing.JList<>();
        botonBorrarEstadosSiguientes = new javax.swing.JButton();
        campoTextoEstadosSiguientes = new javax.swing.JTextField();
        ContadorDeEstadosSiguientes = new javax.swing.JLabel();
        NombreDelEstadoSiguiente = new javax.swing.JLabel();
        AtrasEstados1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        modeloEstadosSiguientes2 = new DefaultListModel();
        ListaDeEstadosSiguientesTabla2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JlabelFondo4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        modeloEquipo = new DefaultListModel();
        ListaDeEquipoTabla = new javax.swing.JList<>();
        campoTextoEquipo = new javax.swing.JTextField();
        BotonAgregarEquipo1 = new javax.swing.JButton();
        botonBorrarEquipo1 = new javax.swing.JButton();
        atrasEquipo = new javax.swing.JButton();
        JlabelFondo5 = new javax.swing.JLabel();
        JlabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(51, 255, 255));
        salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(102, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icon (1).png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 0, 30, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregar.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/instalar-el-paquete-icono-5544-16.png"))); // NOI18N
        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 110, -1));

        ListaDeItemsTabla.setModel(modelo);
        ListaDeItemsTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDeItemsTabla.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(ListaDeItemsTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, -1));

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 110, -1));

        campoTextoItem.setText("Nombre del item");
        campoTextoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoItemActionPerformed(evt);
            }
        });
        jPanel1.add(campoTextoItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, -1));

        ContadorDeLista.setText("Cantidad de la lista");
        jPanel1.add(ContadorDeLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, -1));

        BotonModificarItem.setText("Modificar Item");
        BotonModificarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarItemActionPerformed(evt);
            }
        });
        jPanel1.add(BotonModificarItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 110, -1));

        jButton4.setText("Asignar equipo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 110, -1));

        PrioridadItem.setText("Prioridad");
        PrioridadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrioridadItemActionPerformed(evt);
            }
        });
        jPanel1.add(PrioridadItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, -1));

        JlabelFondo1.setForeground(new java.awt.Color(255, 255, 255));
        JlabelFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondo-celeste-oscuro-6269.jpg"))); // NOI18N
        jPanel1.add(JlabelFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 280));

        jTabbedPane1.addTab("Items", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTabbedPane1.addTab("tab2", jScrollPane2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregarEstado.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregarEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/instalar-el-paquete-icono-5544-16.png"))); // NOI18N
        BotonAgregarEstado.setText("Agregar");
        BotonAgregarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarEstadoActionPerformed(evt);
            }
        });
        jPanel3.add(BotonAgregarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 20, 170, -1));

        ListaDeEstadosTabla.setModel(modeloEstado);
        ListaDeEstadosTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDeEstadosTabla.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(ListaDeEstadosTabla);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, -1));

        botonBorrarEstado.setText("Borrar");
        botonBorrarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarEstadoActionPerformed(evt);
            }
        });
        jPanel3.add(botonBorrarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 170, -1));

        campoTextoEstado.setText("nombre del Estado");
        campoTextoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoEstadoActionPerformed(evt);
            }
        });
        jPanel3.add(campoTextoEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, -1));

        ContadorDeEstados.setText("Cantidad de la lista");
        jPanel3.add(ContadorDeEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, -1));

        jButton2.setText("posibles Siguientes estados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 170, -1));
        jPanel3.add(NombreDelItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 130, -1));

        AtrasEstados.setText("atras");
        AtrasEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasEstadosActionPerformed(evt);
            }
        });
        jPanel3.add(AtrasEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 103, 170, 30));

        JlabelFondo3.setForeground(new java.awt.Color(255, 255, 255));
        JlabelFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondo-celeste-oscuro-6269.jpg"))); // NOI18N
        jPanel3.add(JlabelFondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 280));

        jTabbedPane1.addTab("Estados", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregarEstadosSiguientes.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregarEstadosSiguientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/instalar-el-paquete-icono-5544-16.png"))); // NOI18N
        BotonAgregarEstadosSiguientes.setText("Agregar");
        BotonAgregarEstadosSiguientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarEstadosSiguientesActionPerformed(evt);
            }
        });
        jPanel4.add(BotonAgregarEstadosSiguientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        ListaDeEstadosSiguientesTabla.setModel(modeloEstadosSiguientes);
        ListaDeEstadosSiguientesTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDeEstadosSiguientesTabla.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(ListaDeEstadosSiguientesTabla);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 220, -1));

        botonBorrarEstadosSiguientes.setText("Borrar");
        botonBorrarEstadosSiguientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarEstadosSiguientesActionPerformed(evt);
            }
        });
        jPanel4.add(botonBorrarEstadosSiguientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, -1));

        campoTextoEstadosSiguientes.setText("nombre del Estado");
        campoTextoEstadosSiguientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoEstadosSiguientesActionPerformed(evt);
            }
        });
        jPanel4.add(campoTextoEstadosSiguientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, -1));

        ContadorDeEstadosSiguientes.setText("Cantidad de la lista");
        jPanel4.add(ContadorDeEstadosSiguientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 10));
        jPanel4.add(NombreDelEstadoSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 130, -1));

        AtrasEstados1.setText("atras");
        AtrasEstados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasEstados1ActionPerformed(evt);
            }
        });
        jPanel4.add(AtrasEstados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 100, -1));

        ListaDeEstadosSiguientesTabla2.setModel(modeloEstadosSiguientes2);
        ListaDeEstadosSiguientesTabla2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDeEstadosSiguientesTabla2.setRequestFocusEnabled(false);
        jScrollPane5.setViewportView(ListaDeEstadosSiguientesTabla2);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, -1));

        jLabel1.setText("Selecione un estado:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 20));

        jLabel2.setText("Posibles estados siguientes:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 210, -1));

        JlabelFondo4.setForeground(new java.awt.Color(255, 255, 255));
        JlabelFondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondo-celeste-oscuro-6269.jpg"))); // NOI18N
        jPanel4.add(JlabelFondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 280));

        jTabbedPane1.addTab("Sigientes", jPanel4);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaDeEquipoTabla.setModel(modeloEquipo);
        ListaDeEquipoTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDeEquipoTabla.setRequestFocusEnabled(false);
        jScrollPane6.setViewportView(ListaDeEquipoTabla);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, -1));

        campoTextoEquipo.setText("nombre del Miembro");
        campoTextoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoEquipoActionPerformed(evt);
            }
        });
        jPanel2.add(campoTextoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, -1));

        BotonAgregarEquipo1.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregarEquipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/instalar-el-paquete-icono-5544-16.png"))); // NOI18N
        BotonAgregarEquipo1.setText("Agregar");
        BotonAgregarEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarEquipo1ActionPerformed(evt);
            }
        });
        jPanel2.add(BotonAgregarEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 20, 170, -1));

        botonBorrarEquipo1.setText("Borrar");
        botonBorrarEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarEquipo1ActionPerformed(evt);
            }
        });
        jPanel2.add(botonBorrarEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 170, -1));

        atrasEquipo.setText("atras");
        atrasEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasEquipoActionPerformed(evt);
            }
        });
        jPanel2.add(atrasEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 170, -1));

        JlabelFondo5.setForeground(new java.awt.Color(255, 255, 255));
        JlabelFondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondo-celeste-oscuro-6269.jpg"))); // NOI18N
        jPanel2.add(JlabelFondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 280));

        jTabbedPane1.addTab("equipo", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        JlabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        JlabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondo-celeste-oscuro-6269.jpg"))); // NOI18N
        getContentPane().add(JlabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void campoTextoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoItemActionPerformed
        
    }//GEN-LAST:event_campoTextoItemActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if(modelo.getSize()>0)
        {int n =ListaDeItemsTabla.getSelectedIndex();
            modelo.removeElementAt(n);            
        listaDeItems.remove(n);
        
            ListaDeItemsTabla.setSelectedIndex(0);
        }
        ContadorDeLista.setText(String.valueOf(modelo.getSize()));
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        modelo.addElement(campoTextoItem.getText());
        Item nuevo =  new Item(campoTextoItem.getText());
        Equipo equipo= new Equipo();
        
        //equipo.setLider(lider);
        nuevo.setEquipo(equipo);
        nuevo.setPrioridad(PrioridadItem.getText());
        listaDeItems.add(nuevo);
        
        campoTextoItem.setText("");
        campoTextoItem.requestFocus();
        ListaDeItemsTabla.setSelectedIndex(0);
        ContadorDeLista.setText(String.valueOf(modelo.getSize()));
        listaDeItems.forEach((i) -> {
            System.out.println (i.getNombre()); //Muestra cada uno de los nombres dentro de listaDeNombres
        });
        
        
        
        
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonAgregarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarEstadoActionPerformed
        modeloEstado.addElement(campoTextoEstado.getText());
         Estado nuevo =  new Estado(campoTextoEstado.getText());
        listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).agregarListaDeEstados(nuevo);
        campoTextoEstado.setText("");
        campoTextoEstado.requestFocus();
        ListaDeEstadosTabla.setSelectedIndex(0);
        ContadorDeEstados.setText(String.valueOf(modeloEstado.getSize()));
     
    }//GEN-LAST:event_BotonAgregarEstadoActionPerformed

    private void botonBorrarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarEstadoActionPerformed
      if(modeloEstado.getSize()>0)
        {int n =ListaDeEstadosTabla.getSelectedIndex();
            modeloEstado.removeElementAt(n);
            listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).borrarListaDeEstados(n);
            ListaDeEstadosTabla.setSelectedIndex(0);
    }
        ContadorDeEstados.setText(String.valueOf(modeloEstado.getSize()));
        
    }//GEN-LAST:event_botonBorrarEstadoActionPerformed

    private void campoTextoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoEstadoActionPerformed

    private void BotonModificarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarItemActionPerformed
        jTabbedPane1.setEnabledAt(2,true);
        jTabbedPane1.setSelectedIndex(2);
        NombreDelItem.setText(ListaDeItemsTabla.getSelectedValue());
        jTabbedPane1.setEnabledAt(0,false);
        listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).getListaDeEstados().forEach((i) -> {
            modeloEstado.addElement(i.getNombre()); 
        });
        
    }//GEN-LAST:event_BotonModificarItemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setEnabledAt(3,true);
        jTabbedPane1.setSelectedIndex(3);
        NombreDelEstadoSiguiente.setText(ListaDeEstadosTabla.getSelectedValue());
        jTabbedPane1.setEnabledAt(2,false);
        listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).getListaDeEstados().forEach((i) -> {
            modeloEstadosSiguientes2.addElement(i.getNombre()); 
             
        }
        );
        listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).getListaDeEstados().get(ListaDeEstadosTabla.getSelectedIndex()).getSiguientesEstados().forEach((i) -> {
            modeloEstadosSiguientes.addElement(i.getNombre()); 
        });     
        
        ;
        //int n =ListaDeEstadosTabla.getSelectedIndex();
        //listaDeEstados.get(n).AddSiguienteEstado();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotonAgregarEstadosSiguientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarEstadosSiguientesActionPerformed
        modeloEstadosSiguientes.addElement(modeloEstadosSiguientes2.getElementAt(ListaDeEstadosSiguientesTabla2.getSelectedIndex()));
        int n =ListaDeEstadosTabla.getSelectedIndex();
        Estado nuevo= listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).getListaDeEstados().get(ListaDeEstadosSiguientesTabla2.getSelectedIndex());
        listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).getListaDeEstados().get(n).AddSiguienteEstado(nuevo);
        //listaDeEstados.get(n).AddSiguienteEstado(nuevo);
        campoTextoEstadosSiguientes.setText("");
        campoTextoEstadosSiguientes.requestFocus();
        ListaDeEstadosSiguientesTabla.setSelectedIndex(0);
        ListaDeEstadosSiguientesTabla2.setSelectedIndex(0);
        ContadorDeEstadosSiguientes.setText(String.valueOf(modeloEstado.getSize()));
     
    }//GEN-LAST:event_BotonAgregarEstadosSiguientesActionPerformed

    private void botonBorrarEstadosSiguientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarEstadosSiguientesActionPerformed
      if(modeloEstadosSiguientes.getSize()>0)
        {int n =ListaDeEstadosSiguientesTabla.getSelectedIndex();
            modeloEstadosSiguientes.removeElementAt(n);
            listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).getListaDeEstados().get(ListaDeEstadosTabla.getSelectedIndex()).
                    borrarSiguienteEstado(n);
            ListaDeEstadosSiguientesTabla.setSelectedIndex(0);
    }
        ContadorDeEstadosSiguientes.setText(String.valueOf(modeloEstado.getSize()));
        
    }//GEN-LAST:event_botonBorrarEstadosSiguientesActionPerformed

    private void AtrasEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasEstadosActionPerformed
        jTabbedPane1.setEnabledAt(0,true);    
        jTabbedPane1.setSelectedIndex(0);
            modeloEstado.removeAllElements(); 
        jTabbedPane1.setEnabledAt(2,false);     
        
    }//GEN-LAST:event_AtrasEstadosActionPerformed

    private void AtrasEstados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasEstados1ActionPerformed
        jTabbedPane1.setEnabledAt(2,true);    
        jTabbedPane1.setSelectedIndex(2);
          modeloEstadosSiguientes.removeAllElements();
          modeloEstadosSiguientes2.removeAllElements();
        jTabbedPane1.setEnabledAt(3,false);     
        
    }//GEN-LAST:event_AtrasEstados1ActionPerformed

    private void campoTextoEstadosSiguientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoEstadosSiguientesActionPerformed
         
    }//GEN-LAST:event_campoTextoEstadosSiguientesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           jTabbedPane1.setEnabledAt(4,true);    
        jTabbedPane1.setSelectedIndex(4);
        listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).getEquipo().getMiembros().forEach((i) -> {
            modeloEquipo.addElement(i.getNombre()); 
        });
        jTabbedPane1.setEnabledAt(0,false); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void PrioridadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrioridadItemActionPerformed
        
    }//GEN-LAST:event_PrioridadItemActionPerformed

    private void campoTextoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoEquipoActionPerformed

    private void BotonAgregarEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarEquipo1ActionPerformed
        modeloEquipo.addElement(campoTextoEquipo.getText());
        Miembro nuevo =  new Miembro(campoTextoEquipo.getText());
        listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).getEquipo().agregarMiembro(nuevo);
        
        campoTextoEquipo.setText("");
        campoTextoEquipo.requestFocus();
        ListaDeEquipoTabla.setSelectedIndex(0);
                
    }//GEN-LAST:event_BotonAgregarEquipo1ActionPerformed

    private void botonBorrarEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarEquipo1ActionPerformed
        if(modeloEquipo.getSize()>0)
        {int n =ListaDeEquipoTabla.getSelectedIndex();
            modeloEquipo.removeElementAt(n);
            listaDeItems.get(ListaDeItemsTabla.getSelectedIndex()).getEquipo().borrarMiembro(n);
            ListaDeEquipoTabla.setSelectedIndex(0);
    }
       
    }//GEN-LAST:event_botonBorrarEquipo1ActionPerformed

    private void atrasEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasEquipoActionPerformed
        jTabbedPane1.setEnabledAt(0,true);    
        jTabbedPane1.setSelectedIndex(0);
        modeloEquipo.removeAllElements(); 
        jTabbedPane1.setEnabledAt(4,false);     
                // TODO add your handling code here:
    }//GEN-LAST:event_atrasEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasEstados;
    private javax.swing.JButton AtrasEstados1;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonAgregarEquipo1;
    private javax.swing.JButton BotonAgregarEstado;
    private javax.swing.JButton BotonAgregarEstadosSiguientes;
    private javax.swing.JButton BotonModificarItem;
    private javax.swing.JLabel ContadorDeEstados;
    private javax.swing.JLabel ContadorDeEstadosSiguientes;
    private javax.swing.JLabel ContadorDeLista;
    private javax.swing.JLabel JlabelFondo;
    private javax.swing.JLabel JlabelFondo1;
    private javax.swing.JLabel JlabelFondo3;
    private javax.swing.JLabel JlabelFondo4;
    private javax.swing.JLabel JlabelFondo5;
    private javax.swing.JList<String> ListaDeEquipoTabla;
    private DefaultListModel modeloEquipo;
    private javax.swing.JList<String> ListaDeEstadosSiguientesTabla;
    private DefaultListModel modeloEstadosSiguientes;
    private javax.swing.JList<String> ListaDeEstadosSiguientesTabla2;
    private DefaultListModel modeloEstadosSiguientes2;
    private javax.swing.JList<String> ListaDeEstadosTabla;
    private DefaultListModel modeloEstado;
    private javax.swing.JList<String> ListaDeItemsTabla;
    private DefaultListModel modelo;
    private javax.swing.JLabel NombreDelEstadoSiguiente;
    private javax.swing.JLabel NombreDelItem;
    private javax.swing.JTextField PrioridadItem;
    private javax.swing.JButton atrasEquipo;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBorrarEquipo1;
    private javax.swing.JButton botonBorrarEstado;
    private javax.swing.JButton botonBorrarEstadosSiguientes;
    private javax.swing.JTextField campoTextoEquipo;
    private javax.swing.JTextField campoTextoEstado;
    private javax.swing.JTextField campoTextoEstadosSiguientes;
    private javax.swing.JTextField campoTextoItem;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
